- name: Check supported operating system
  ansible.builtin.assert:
    that:
      - ansible_facts.os_family == 'RedHat'
      - ansible_facts.distribution_major_version == '9'
    fail_msg: nginx_modules supports Enterprise Linux 9 only

- name: Read installed Nginx version
  ansible.builtin.command: nginx -v
  register: nginx_modules_nginx_version
  changed_when: false
  check_mode: false

- name: Copy Nginx modules RPM signing key
  ansible.builtin.copy:
    src: "{{ nginx_modules_gpg_key }}"
    dest: "/etc/pki/rpm-gpg/{{ nginx_modules_gpg_key }}"
    owner: root
    group: root
    mode: "0644"

- name: Import Nginx modules RPM signing key
  ansible.builtin.rpm_key:
    key: "/etc/pki/rpm-gpg/{{ nginx_modules_gpg_key }}"
    state: present

- name: Copy Nginx module RPMs
  ansible.builtin.copy:
    src: "{{ nginx_modules_rpm_directory }}/nginx-module-{{ item }}.rpm"
    dest: "/var/tmp/nginx-module-{{ item }}.rpm"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ nginx_modules }}"

- name: Install Nginx module RPMs
  ansible.builtin.dnf:
    name: "/var/tmp/nginx-module-{{ item }}.rpm"
    state: present
    disable_gpg_check: false
  loop: "{{ nginx_modules }}"
  notify: Validate and reload Nginx

- name: Enable Nginx modules
  ansible.builtin.copy:
    content: "load_module modules/{{ nginx_modules_shared_objects[item] }};\n"
    dest: "/usr/share/nginx/modules/50-{{ item }}.conf"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ nginx_modules }}"
  notify: Validate and reload Nginx

- name: Validate Nginx configuration
  ansible.builtin.command: nginx -t
  changed_when: false
