- name: Validate Nginx configuration
  ansible.builtin.command: nginx -t
  changed_when: false
  listen: Validate and reload Nginx

- name: Reload Nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
  listen: Validate and reload Nginx

