nginx_modules:
  - nchan

# Downloaded GitHub Release RPMs, copied to the Ansible controller beforehand.
nginx_modules_rpm_directory: nginx-modules
nginx_modules_gpg_key: RPM-GPG-KEY-nginx-modules

nginx_modules_shared_objects:
  geoip2: ngx_http_geoip2_module.so
  nchan: ngx_nchan_module.so
