- name: Install nginx.org dynamic modules
  hosts: web
  become: true
  roles:
    - role: nginx_modules
      nginx_modules:
        - geoip2
        - nchan
      nginx_geoip2_databases:
        - country
        - city
        - asn
